### PR TITLE
Upgrade stm-containers and Spock

### PR DESCRIPTION
**Pull request by adinapoli-mndc**
Depends on https://github.com/oscoin/gossip/pull/20. Part of #388.

This PR upgrades `Spock` and `gossip` so that we can drop the old dependencies on `focus` and `stm-containers`.

### CODE REVIEW

**Comment by adinapoli-mndc** [comment]
@kim yup, sounds good. I also think it's safer for us to first merge the relevant PR in `gossip` so that I can actually use a "stable" commit SHA in the snapshot. It happened to me in the past that I did brake the world by depending on a SHA which was later force pushed, hehe.

**Comment by adinapoli-mndc** [comment]
@kim apparently that wasn't sufficient 🙈 : 

```
iproute-1.7.7: configure                                                                            
iproute-1.7.7: build                                                                                
iproute-1.7.7: copy/register   
Progress 208/285               

--  While building package HTTP-4000.3.12 using:
      /Users/adinapoli/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 configure --with-ghc=/Users/adinapoli/.stack/programs/x86_64-osx/ghc-8.6.3/bin/ghc --with-ghc-pkg=/Users/adinapoli/.stack/programs/x86_64-osx/ghc-8.6.3/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/pkgdb --libdir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/lib --bindir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/bin --datadir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/share --libexecdir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/libexec --sysconfdir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/etc --docdir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/doc/HTTP-4000.3.12 --htmldir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/doc/HTTP-4000.3.12 --haddockdir=/Users/adinapoli/.stack/snapshots/x86_64-osx/custom-oscoin-deps-13.10-wlB8UstHUSt1/8.6.3/doc/HTTP-4000.3.12 --dependency=array=array-0.5.3.0 --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=mtl=mtl-2.2.2 --dependency=network=network-3.0.1.0-7RbzcswhVnf7DEgakRBVs9 --dependency=network-uri=network-uri-2.6.1.0-K75fCYvLQE41EntOQ30cqK --dependency=parsec=parsec-3.1.13.0 --dependency=time=time-1.8.0.2
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/adinapoli/work/clients/monadic/oscoin/.stack-work/logs/HTTP-4000.3.12.log

    Configuring HTTP-4000.3.12...
    Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3: Encountered missing dependencies:
    mtl (>=1.1.1.0 && <1.2) && ==2.2.2,
    network ((>=2.2.1.8 && <2.6) && ==3.0.1.0 || (>=2.6 && <2.9) && ==3.0.1.0) ||
    (>=2.2.1.8 && <2.6) && ==3.0.1.0 || (>=2.6 && <2.9) && ==3.0.1.0
```

Although `HTTP` can be bumped, the next dependency which has a stringent `network` upper bound is `socks`, which hasn't been updated for a while.

Should we surrender yet?

**Comment by kim** [comment]
TFW you realise you depend on ancient stuff from the future you didn’t even know you needed 

It’s epic: https://github.com/haskell-infra/hackage-trustees/issues/207

Maybe we can wait for a little while, I’ve got full command of the preprocessor :flex:

**Comment by adinapoli-mndc** [comment]
Welcome to the future 😂 

If you don't mind, I will merge this one now, as it looks like the `socks` saga will continue for a while, and we can issue a separate PR either when that is resolved or if you master your CPP-fu 😁

**Pull request merged**
